spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management_db
    username: root
    password: Ronald2021!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: user-management
  messages:
    basename: messages

admin:
  email:
    address: chiwesheronny@gmail.com
    server: 192.168.101.60
    port: 25
  default-user:
    username: ronald
    password: Password123!

session:
  expireTime: 18000
  jobToDelete: "0 0 * * * *"